#ifndef ENUM_STATUS_H
#define ENUM_STATUS_H

typedef enum {
    ENUMSTATUS_OK,
    ENUMSTATUS_NOT_POSSIBLE_HERE,
    ENUMSTATUS_NOT_POSSIBLE_NOW,
    ENUMSTATUS_TOO_FAR_AWAY,
    ENUMSTATUS_OTHER_PROBLEM
} EnumStatus;

#endif
